Hardware setup variables table fixes (#88)
* fix AttributeError: 'NoneType' object has no attribute 'text'

* remove excess code

- if statements in save() were unnecessary because the refresh_save_button() already contains the logic that checks for a edits/changes from the starting values
- no reason to have hw_var in the setup_variables dictionary

* clearer variable and function names